### ISSUE TITLE
Improve story pages navigations and sections

### ISSUE THREAD

**Issue by ctwhome** [RECEIPT-H2020/TerriaMap#119]

**Comment by goord** [comment]
At the workshop we observed several people using the sections to go through the story instead of the small buttons at the bottom, so this definitely needs to be improved. I think we as a team are also biased because the sections came later, and so our focus is still on the small buttons for navigation

**Comment by Maartenvm** [comment]
- [ ] Change mobile view as follows (old -> new)

![Image](https://user-images.githubusercontent.com/1705817/198287756-b10126f6-43c8-438f-b4c4-c240d4f85dc0.png)





- [ ] Change desktop view as follows (old -> new)

![Image](https://user-images.githubusercontent.com/1705817/198286749-137e5b34-fb33-4082-870e-ae7f35834cb5.png)

**Comment by sjvrijn** [comment]
Current status in the [terriajs/navigation-update](https://github.com/RECEIPT-H2020/terriajs/tree/navigation-update) branch:
- circles in footer removed
- page counter added (although text lay-out still needs to be improved)
- navigation arrows increased in size

![Screenshot 2022-12-15 105348](https://user-images.githubusercontent.com/8833517/207829590-55c5bcd3-1e57-40f8-8fdd-df2a57ce0c79.png)
