### ISSUE TITLE
Refactor component definition 

### ISSUE THREAD

**Issue by bpmweel** [RECEIPT-H2020/TerriaMap#80]
- [ ] Refactor to class-based definition or latest functional react classes
- [x] Add async-await babel plugin
- [x] Prefix all receipt components with RC

**Comment by ctwhome** [comment]
I consider this task finish. But as a note, I only refactor those components that were made by us from scratch. 

Components where we introduced small or not that small changes to terria map I didn't. That could break code when pulling changes from TerriaJS to update to their latest version. 

Note: most components created around 2015 in terria use mixing, which are rather obsolete since a few years ago. I tried some refactoring following HOC (Composable with High Order Components), [see post](https://medium.com/@stides303/replacing-mixins-in-react-1f78ff567919#:~:text=Mixins%20extend%20the%20class%20they,they%20communicate%20through%20props%20instead.), but when wrapping the components the layout breaks. I would either leave them as they are since they don't break functionality or create a new technical debt separately for classes with mixins.
